### ISSUE TITLE
Does FuriganaTextView have UITextView delegate methods?

### ISSUE THREAD

**Issue by alamodey** [lingochamp/FuriganaTextView#10]
I would like to use the FuriganaTextView display Japanese text that can be selected (which would then display the selected text's definition). In order to do this I need to use a UITextView delegate method called textViewDidChangeSelection. 

But it doesn't appear that FuriganaTextView inherits the UITextView's delegate methods?

**Comment by eyeplum** [comment]
Since `FuriganaTextView` has-a `UITextView`, it's certainly possible to implement the required delegate method and achieve that. Please feel free to fork and implement it :)

I think at this point unless you intend to support iOS 7 and earlier, using `CTRubyAnnotation` in CoreText is probably a better approach. `FurigataTextView` was originally created for this reason and is no longer maintained.

**Comment by alamodey** [comment]
Hi, can you explain how to implement the delegate methods? I tried to set the delegate? I tried to do textView.delegate = self but it gives an error "Value of type 'FuriganaTextView' has no member 'delegate'"

Do you have much experience with kCTRubyAnnotationAttributeName? I am not able to get ruby text to display inside a UITextView.

**Comment by eyeplum** [comment]
`FuriganaTextView` is not a `UITextView`, instead, it "has-a" `UITextView` (see https://github.com/lingochamp/FuriganaTextView/blob/master/src/FuriganaTextView.swift#L54). So one way this can be done is to modify `FuriganaTextView` to implement `UITextViewDelegate` and the required delegate method. Another way I can think of is to use [this](https://github.com/lingochamp/FuriganaTextView/blob/master/src/FuriganaTextView.swift#L24) public calculated property, this returns a reference to the underlying `UITextView` used by `FuriganaTextView` so you can then assign a delegate to the `UITextView`.

As for CTRubyAnnotation, I don't think it works for UITextView since I believe it's a CoreText only attribute. You will have to write your own text view and use CoreText as a text shaping engine. Basically you will need to shape runs of text using CoreText and draw then into a canvas view (e.g. the content view of a `UIScrollView`).

**Comment by alamodey** [comment]
On the second option where I set textView.contentView.delegate = self

Then within that view controller that now adopts UITextViewDelegate, how come when I highlight text nothing goes through textViewDidChangeSelection?

**Comment by eyeplum** [comment]
I'm not sure, but I get a feeling it's not in scope of this repo. Does it work as intended in a normal `UITextView`?

**Comment by alamodey** [comment]
I just tried it and it works with a normal UITextView. I feel like there's something basic I'm missing here, like even if I set the controller to be the UITextView Delegate, maybe it can't be the delegate of a property/subview?

**Comment by eyeplum** [comment]
It might be related to how the underlying `UITextView` is configured (see [here](https://github.com/lingochamp/FuriganaTextView/blob/master/src/FuriganaTextView.swift#L117)).

Unfortunately my current setup (macOS 11 + Xcode 12) no longer works for this repo so I can't pin point the exact reason.
