### ISSUE TITLE
Furigana array needs to be sorted. 

### ISSUE THREAD

**Issue by jtoronto** [lingochamp/FuriganaTextView#3]
This textview works great, but you might want to add to the documentation that the furigana array you feed it needs to be sorted according to range location.

**Comment by eyeplum** [comment]
Hi @jtoronto, I'm glad the text view is useful 😇
And thanks for the feedback, I will look into this.

**Comment by iswearwxp** [comment]
hi, should you code this with object-c? It's very useful for me :)

发自我的 iPhone

**Comment by eyeplum** [comment]
Hello @iswearwxp, I think it's a little off the topic for this issue.
But I'm not planning to do this in Objective-C. If you are targeting iOS 7.0 and later, maybe you can use this as-is since Swift provides an Objective-C interoperability.
If you still have questions, please open a new issue so we can have a more detailed discussion.
Thanks.
